universe    = vanilla     
executable  = condor.sh

#---- Python File -------
pyFile  = serial.py 
pylocation = /home/arkajitmandal/py3.tar.gz  
#------------------------

Arguments = $(pyFile)

transfer_input_files =   $(pyFile), Model, Method, input.txt, $(pylocation)
#transfer_output_files = Pii.txt

log    = log/job.log
error  = log/job.err
output = log/job.out


# Require nodes that can access the correct OSG modules
Requirements = (HAS_MODULES =?= true) && (OSGVO_OS_STRING == "RHEL 7")

request_cpus    = 1 
request_memory  = 4GB
request_disk    = 2GB

queue  

