+SingularityImage = "/cvmfs/singularity.opensciencegrid.org/opensciencegrid/osgvo-ubuntu-20.04:latest"
executable  = condor.sh

#---- Python File -------
pyFile  = serial.py 
#input   = input.txt
#output  = output
#------------------------

Arguments = $(pyFile) $(input) $(output) $(ProcID)

transfer_input_files =   $(pyFile), Model, Method, input.txt 

# log    = log/job.log
error  = output/job.err
output = output/job.out


# Require nodes that can access the correct OSG modules

request_cpus    = 1 
request_memory  = 4GB
request_disk    = 2GB