+SingularityImage = "/cvmfs/singularity.opensciencegrid.org/opensciencegrid/osgvo-ubuntu-20.04:latest"
executable  = condor.sh

#---- Python File -------
pyFile  = serial.py 
#input   = input.txt
#output  = output
#------------------------

Arguments = $(pyFile) $(input) $(outFold) $(ProcID)

transfer_input_files =   $(pyFile), Model, Method, input.txt 
transfer_output_files =  $(outFold)
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# log    = $(outFold)/job.log
error  = $(outFold)/job.err
output = $(outFold)/job.out


# Require nodes that can access the correct OSG modules

request_cpus    = 1 
request_memory  = 4GB
request_disk    = 2GB